Update Sec.yml

diff --git a/.github/workflows/Sec.yml b/.github/workflows/Sec.yml
--- a/.github/workflows/Sec.yml
+++ b/.github/workflows/Sec.yml
@@ -1,4 +1,4 @@
-name: Sec
+name: Pipeline Secure test
 
 on:
   push:
@@ -10,34 +10,60 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Login to Docker Hub
-      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin
+      - name: Login to Docker Hub
+        run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin
 
-    - name: Build and push Docker image
-      run: |
-        docker build -t ${{ secrets.USER }}/devsecops:2.0 .
-        docker push ${{ secrets.USER }}/devsecops:2.0
+      - name: Build and push Docker image
+        run: |
+          docker build -t ${{ secrets.USER }}/devsecops:2.0 .
+          docker push ${{ secrets.USER }}/devsecops:2.0
 
   sast_test:
-    needs: build
     runs-on: ubuntu-latest
+    needs: [build]
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Install Bandit
-      run: pip install bandit
+      - name: Install Bandit
+        run: pip install bandit
 
-    - name: Run Bandit SAST scan
-      run: bandit -r . -f json -o bandit-output.json || true  # Ignore failures to prevent pipeline from failing
+      - name: Run Bandit SAST scan
+        run: |
+          bandit -r . -f json -o bandit-output.json || true  # Ignore failures to prevent pipeline from failing
 
-    - name: Archive Bandit output
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: bandit_output
-        path: bandit-output.json
+      - name: Archive Bandit output
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: bandit_output
+          path: bandit-output.json
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: [sast_test]
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Deploy to Production
+        run: |
+          docker pull ${{ secrets.USER }}/devsecops:2.0
+          docker stop devsecops || true  # Stop the container if it's already running
+          docker run -d --name devsecops -p 80:80 ${{ secrets.USER }}/devsecops:2.0
+
+  notify_discord:
+    runs-on: ubuntu-latest
+    needs: deploy
+
+    steps:
+      - name: Send Discord Notification
+        env:
+          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD }}
+        run: |
+          curl -X POST -H "Content-Type: application/json" -d '{"content": "Pipeline concluída com sucesso!"}' ${{ secrets.DISCORD }}
